USE [master];
GO

IF NOT EXISTS (SELECT * FROM sys.sql_logins WHERE name = 'JoaquinPrueba')
BEGIN
    CREATE LOGIN [JoaquinPrueba] WITH PASSWORD = 'ClaveSegura24.', CHECK_POLICY = OFF;
    ALTER SERVER ROLE [sysadmin] ADD MEMBER JoaquinPrueba;
END
GO

CREATE DATABASE GESTION_COMPRA;

USE GESTION_COMPRA;

CREATE TABLE ORDEN_DE_COMPRA(
	ID_ORDEN INT IDENTITY(1,1) PRIMARY KEY,
	CLIENTE VARCHAR(50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
	TOTAL FLOAT NOT NULL
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_PRODUCTO VARCHAR(255) NOT NULL,
	PRECIO_PRODUCTO FLOAT NOT NULL
);

CREATE TABLE ORDEN_PRODUCTO(
	ID_ORDEN_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
	ID_ORDEN INT NOT NULL, 
	ID_PRODUCTO INT NOT NULL,
	CONSTRAINT FK_ORDEN_COMPRA_ORDEN_PRODUCTO FOREIGN KEY (ID_ORDEN)
	REFERENCES ORDEN_DE_COMPRA(ID_ORDEN)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT FK_PRODUCTO_ORDEN_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
	REFERENCES PRODUCTO (ID_PRODUCTO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);